<?php

// Original introductory notes and exercises; each row follows the existing course module order.
return [
'C01' => <<<'LESSONS'
Introduction to Information Systems|Sistem informasi menggabungkan manusia, prosedur, data, dan teknologi untuk mendukung kegiatan organisasi. Aplikasi kasir baru berguna ketika transaksi dicatat dengan benar dan laporannya dipakai untuk keputusan stok.|Gambarkan input, proses, output, dan pengguna pada sistem peminjaman buku kampus.
People, Process, Data & Technology|Kesalahan informasi dapat berasal dari proses, bukan hanya perangkat lunak. Jika petugas tidak mencatat pengembalian buku, database tetap menampilkan pinjaman aktif meskipun aplikasinya berjalan normal.|Untuk kasus buku terlambat tercatat, tentukan perbaikan pada petugas, prosedur, struktur data, dan aplikasi.
Information Systems in Organizations|Sistem transaksi merekam kegiatan harian. Laporan manajerial merangkum kegiatan tersebut; dukungan keputusan membantu membandingkan alternatif. Detail yang dibutuhkan petugas berbeda dari ringkasan yang dibutuhkan manajer.|Buat contoh data dan laporan untuk petugas perpustakaan, kepala layanan, dan pimpinan kampus.
Business Models & Value Chains|Model bisnis menjelaskan bagaimana organisasi menciptakan dan memperoleh nilai. Rantai nilai memeriksa kegiatan yang menghasilkan nilai itu. Otomasi kegiatan yang tidak diperlukan belum tentu memperbaiki hasil.|Petakan pemesanan sampai pengiriman toko daring. Tandai biaya, nilai bagi pelanggan, dan satu hambatan.
Enterprise Information Systems|ERP menghubungkan proses internal seperti persediaan dan keuangan. CRM mendukung hubungan dengan pelanggan. Integrasi membutuhkan identitas data yang konsisten, misalnya satu kode pelanggan di beberapa sistem.|Jelaskan akibat jika pelanggan yang sama memiliki tiga kode berbeda di penjualan, pengiriman, dan penagihan.
Digital Transformation & IS Ethics|Transformasi digital mengubah cara kerja dan layanan, bukan sekadar memindahkan formulir ke layar. Pengumpulan data perlu tujuan, akses yang sesuai, serta pertimbangan dampak bagi orang yang datanya digunakan.|Rancang layanan antrean kampus. Sebutkan data minimum, siapa yang boleh melihatnya, dan ukuran keberhasilan layanan.
LESSONS,
'C02' => <<<'LESSONS'
Introduction to Business Process|Proses bisnis memiliki pemicu, rangkaian kegiatan, keluaran, dan penerima hasil. Batas proses mencegah analisis melebar. Permintaan pengadaan dimulai saat kebutuhan diajukan dan berakhir ketika barang diterima atau permintaan ditolak.|Tentukan pemicu dan keluaran proses persetujuan kegiatan mahasiswa.
Identifying Business Processes|Identifikasi proses dari pekerjaan yang benar-benar dilakukan. Wawancara pelaksana, amati dokumen, lalu pisahkan aktivitas utama dan pendukung. Struktur organisasi saja tidak menjelaskan aliran pekerjaan lintas bagian.|Daftar lima aktivitas pengadaan dan pemilik masing-masing aktivitas.
AS-IS Process Analysis|AS-IS menggambarkan keadaan saat ini, termasuk antrean, pengulangan, dan pengecualian. Jangan mencampurkan rancangan perbaikan ke peta awal karena sumber masalah menjadi sulit dibuktikan.|Petakan alur persetujuan saat ini dan beri tanda pada pengembalian dokumen yang tidak lengkap.
BPMN Events & Activities|Event menunjukkan sesuatu terjadi; activity menunjukkan pekerjaan dilakukan. Start event memicu proses, end event mengakhirinya. Penamaan aktivitas berupa kata kerja dan objek membantu pembaca memahami langkah.|Gambar start event, pemeriksaan formulir, persetujuan, dan end event untuk permohonan surat.
Gateway, Pool & Lane|Gateway mengatur percabangan atau penggabungan alur. Exclusive gateway memilih satu jalur; parallel gateway menjalankan beberapa jalur. Pool menunjukkan peserta, lane membagi tanggung jawab di dalam peserta.|Modelkan permohonan yang harus diperiksa keuangan dan akademik secara paralel sebelum disetujui.
TO-BE Process Design|TO-BE adalah rancangan yang menjawab masalah pada AS-IS. Setiap perubahan perlu alasan, pemilik, dan ukuran hasil. Menghapus persetujuan mungkin mempercepat proses tetapi juga menghilangkan kontrol.|Usulkan satu langkah yang digabung dan satu kontrol yang tetap diperlukan pada pengadaan.
Process KPI & Bottleneck Analysis|Cycle time mengukur waktu dari awal sampai akhir; waktu kerja aktif berbeda dari waktu menunggu. Bottleneck membatasi keluaran proses. Rata-rata saja dapat menyembunyikan kasus sangat lambat.|Catat waktu sepuluh permohonan, hitung median durasi, lalu tentukan tahapan dengan antrean terpanjang.
Business Process Improvement Project|Perbaikan proses perlu bukti sebelum dan sesudah. Susun peta AS-IS, masalah terukur, TO-BE, risiko perubahan, dan rencana evaluasi. Jelaskan asumsi jika data masih simulasi.|Buat peta dan laporan satu halaman untuk mengurangi waktu persetujuan tanpa menghilangkan pemeriksaan kelengkapan.
LESSONS,
'C03' => <<<'LESSONS'
Introduction to Database & RDBMS|Database relasional menyimpan data dalam tabel. Primary key mengidentifikasi baris; foreign key menjaga hubungan antartabel. NULL menyatakan nilai yang tidak tersedia, bukan angka nol atau string kosong.|Rancang tabel mahasiswa dan peminjaman dengan primary key serta foreign key yang sesuai.
SELECT, WHERE, ORDER BY|SELECT memilih kolom, WHERE menyaring baris, dan ORDER BY menentukan urutan hasil. Tanpa ORDER BY, urutan baris tidak dijamin. Gunakan IS NULL untuk memeriksa nilai kosong SQL.|Tulis SELECT nama FROM mahasiswa WHERE angkatan = 2024 ORDER BY nama; lalu tambahkan filter status aktif.
Aggregate Functions & GROUP BY|COUNT menghitung jumlah, SUM menjumlahkan nilai, dan AVG menghitung rata-rata. GROUP BY membentuk kelompok. WHERE menyaring sebelum agregasi; HAVING menyaring kelompok hasil agregasi.|Hitung jumlah peminjaman per mahasiswa dan tampilkan hanya mahasiswa dengan lebih dari tiga peminjaman.
SQL JOIN|INNER JOIN hanya mempertahankan pasangan yang cocok. LEFT JOIN mempertahankan semua baris kiri dan mengisi sisi kanan dengan NULL jika tidak cocok. Join yang salah dapat menggandakan jumlah baris.|Tampilkan semua mahasiswa, termasuk yang belum pernah meminjam. Jelaskan mengapa COUNT(peminjaman.id) berbeda dari COUNT(*).
Subquery & Common Table Expression|Subquery memakai hasil query lain. CTE dengan WITH memberi nama pada hasil antara agar langkah analisis terbaca. CTE bukan jaminan query lebih cepat; rencana eksekusi tetap perlu diperiksa.|Gunakan WITH untuk menghitung jumlah pinjaman per mahasiswa, lalu cari jumlah yang di atas rata-rata.
INSERT, UPDATE & DELETE|INSERT menambah baris, UPDATE mengubahnya, dan DELETE menghapusnya. UPDATE atau DELETE tanpa WHERE dapat memengaruhi semua baris. Transaksi memungkinkan beberapa perubahan dikonfirmasi bersama atau dibatalkan.|Pada database latihan, jalankan BEGIN, UPDATE terfilter, SELECT verifikasi, lalu ROLLBACK. Jangan memakai database produksi.
Database Design & Normalization|Normalisasi mengurangi duplikasi dan anomali pembaruan. Simpan fakta pelanggan sekali, lalu rujuk lewat ID. Jangan menyimpan daftar barang dipisahkan koma di satu kolom pesanan.|Pisahkan tabel pesanan yang memuat nama pelanggan dan tiga kolom produk menjadi pelanggan, pesanan, dan detail pesanan.
Window Functions|Window function menghitung nilai atas sekumpulan baris tanpa menggabungkan baris menjadi satu seperti GROUP BY. PARTITION BY membagi kelompok, ORDER BY mengatur urutan perhitungan.|Gunakan ROW_NUMBER() OVER (PARTITION BY mahasiswa_id ORDER BY tanggal DESC) untuk menandai pinjaman terbaru.
Indexing & Query Optimization|Index dapat mengurangi baris yang perlu dibaca, tetapi membutuhkan ruang dan biaya saat data berubah. EXPLAIN menunjukkan rencana query. Tidak semua kolom perlu index dan tabel kecil dapat tetap memakai sequential scan.|Bandingkan EXPLAIN query pencarian tanggal sebelum dan sesudah index pada database latihan; catat perubahan rencananya.
SQL Data Analysis Case Study|Analisis harus menjawab pertanyaan yang jelas dan memeriksa kualitas data sebelum menyimpulkan. Agregasi setelah join perlu diuji agar transaksi tidak dihitung berulang.|Buat laporan buku paling dipinjam, pengguna tanpa pinjaman, dan tren bulanan. Sertakan query dan pemeriksaan duplikasi.
LESSONS,
'C04' => <<<'LESSONS'
Excel Fundamentals|Sel memiliki nilai, format, dan rumus yang berbeda. Referensi relatif berubah saat rumus disalin; tanda dolar mengunci baris atau kolom. Format mata uang tidak mengubah makna nilai yang tersimpan.|Buat tabel kuantitas, harga, dan total. Simpan tarif pajak pada satu sel dan gunakan referensi absolut.
Data Cleaning|Pembersihan perlu mempertahankan data mentah agar perubahan dapat ditelusuri. Spasi, format tanggal, dan ID duplikat dapat mengubah hasil ringkasan. Jangan menghapus duplikasi tanpa menentukan kunci bisnis.|Buat salinan tabel transaksi; tandai ID duplikat dan tanggal tidak valid sebelum mengoreksi data.
Logical & Statistical Functions|IF memilih hasil berdasarkan kondisi; COUNTIF dan SUMIF merangkum data sesuai kriteria. Rata-rata sensitif terhadap nilai ekstrem, sedangkan median membantu melihat nilai tengah.|Hitung transaksi di atas target dan bandingkan rata-rata dengan median saat satu transaksi sangat besar ditambahkan.
XLOOKUP / INDEX MATCH|Lookup mencari nilai berdasarkan kunci. Kunci yang tidak unik dapat menghasilkan pasangan yang tidak dimaksudkan. INDEX dengan MATCH memisahkan posisi pencarian dari kolom hasil.|Hubungkan kode produk dengan harga dan tampilkan pesan khusus ketika kode tidak ditemukan.
Pivot Table|PivotTable merangkum data berdasarkan dimensi yang dipilih. Pastikan satu baris sumber mewakili unit yang konsisten dan lakukan refresh ketika sumber berubah.|Ringkas total penjualan per wilayah dan bulan, lalu cocokkan grand total dengan jumlah data sumber.
Data Visualization|Grafik batang cocok untuk perbandingan kategori; grafik garis memperlihatkan perubahan waktu. Judul, satuan, dan sumbu yang jelas membantu mencegah interpretasi salah.|Buat grafik penjualan bulanan dengan satuan rupiah dan jelaskan satu perubahan yang didukung data.
Power Query|Power Query menyimpan langkah transformasi yang dapat dijalankan ulang. Penetapan tipe data, penghapusan kolom, dan penggabungan tabel sebaiknya dilakukan dengan urutan yang dapat dijelaskan.|Impor dua file transaksi bulanan, samakan nama kolom, append, dan verifikasi jumlah baris.
Interactive Excel Dashboard Project|Dashboard yang berguna dimulai dari keputusan pengguna. Batasi indikator utama, tampilkan periode data, dan pastikan filter memengaruhi ringkasan secara konsisten.|Bangun dashboard penjualan dengan filter wilayah, total, tren, dan tiga temuan. Sertakan sheet data mentah dan catatan transformasi.
LESSONS,
'C05' => <<<'LESSONS'
Descriptive Statistics|Mean, median, rentang, dan simpangan baku menjelaskan aspek berbeda dari data. Satu angka ringkasan tidak cukup untuk menggambarkan sebaran. Mean mudah berubah karena outlier.|Untuk 2, 3, 3, 4, 18, hitung mean dan median lalu jelaskan mana yang mewakili nilai tipikal.
Data Distribution|Distribusi memperlihatkan frekuensi dan bentuk nilai. Data dapat miring, memiliki beberapa puncak, atau mengandung outlier. Jangan mengasumsikan distribusi normal tanpa pemeriksaan.|Gambar histogram waktu tunggu dan jelaskan bentuk, pusat, serta nilai ekstremnya.
Probability Fundamentals|Probabilitas bersyarat mengubah peluang berdasarkan informasi yang tersedia. Kejadian independen berbeda dari kejadian saling lepas. Dua kejadian saling lepas tidak bisa terjadi bersamaan.|Dari tabel hadir dan lulus, hitung peluang lulus serta peluang lulus jika hadir; bandingkan keduanya.
Sampling|Sampel membantu mempelajari populasi, tetapi cara pemilihan menentukan bias. Sampel besar dari satu kelompok tetap dapat tidak mewakili kelompok lain.|Rancang sampel mahasiswa lintas angkatan untuk survei layanan perpustakaan dan jelaskan sumber bias yang mungkin tersisa.
Confidence Interval|Interval kepercayaan menggambarkan ketidakpastian estimasi melalui prosedur sampling. Dalam interpretasi frekuentis, parameter tetap; interval yang berubah pada sampel berulang.|Bandingkan dua interval rata-rata dengan ukuran sampel berbeda dan jelaskan pengaruh lebar interval terhadap keputusan.
Hypothesis Testing|Pengujian hipotesis menilai kesesuaian data dengan hipotesis nol. P-value bukan peluang hipotesis nol benar dan bukan ukuran pentingnya efek. Tetapkan kriteria sebelum melihat hasil.|Susun hipotesis untuk perubahan waktu layanan; laporkan ukuran efek dan ketidakpastian, bukan hanya signifikan atau tidak.
Correlation|Korelasi mengukur hubungan, bukan sebab akibat. Outlier dan variabel ketiga dapat menghasilkan hubungan yang menyesatkan. Scatter plot membantu memeriksa pola sebelum memakai koefisien.|Jelaskan mengapa korelasi durasi belajar dan nilai tidak membuktikan setiap tambahan satu jam pasti menaikkan nilai.
Linear Regression|Regresi linear memodelkan hubungan rata-rata respons dan prediktor. Residual membantu memeriksa kecocokan model. Prediksi di luar rentang data memiliki risiko ekstrapolasi.|Modelkan biaya pengiriman dari jarak, periksa residual, dan tulis batas penggunaan prediksi.
LESSONS,
'C06' => <<<'LESSONS'
Python Environment & Syntax|Interpreter mengeksekusi Python; virtual environment memisahkan dependensi proyek. Indentasi menentukan blok kode. Catat versi dependensi agar analisis dapat diulang.|Buat environment latihan, jalankan skrip yang membaca nama file, dan dokumentasikan cara menjalankannya.
Variables & Data Types|Nama variabel merujuk objek dengan tipe tertentu. String angka perlu dikonversi sebelum operasi numerik. Nilai None menandai ketiadaan nilai, bukan angka nol.|Konversi daftar harga berbentuk string menjadi angka dan tangani satu nilai yang tidak valid.
Lists, Dictionaries & Tuples|List adalah urutan yang dapat diubah, tuple adalah urutan yang tidak dapat diubah, dan dictionary memetakan kunci ke nilai. Pilih struktur berdasarkan operasi yang dibutuhkan.|Simpan tiga transaksi sebagai list of dictionaries dan hitung total berdasarkan nama kolom.
Conditions, Loops & Functions|Kondisi memilih cabang, loop mengulang pekerjaan, dan fungsi memisahkan tanggung jawab. Fungsi kecil dengan parameter dan hasil yang jelas mudah diuji.|Buat fungsi klasifikasi keterlambatan peminjaman; uji durasi negatif, nol, dan positif.
NumPy Fundamentals|Array NumPy menyediakan operasi numerik pada kumpulan nilai. Broadcasting menyelaraskan bentuk tertentu, bukan sembarang ukuran array. Periksa shape sebelum operasi.|Buat array harga dan kuantitas, hitung total per transaksi, lalu jelaskan bentuk hasilnya.
Pandas Fundamentals|DataFrame menyimpan kolom berlabel dan index. Pemilihan kolom, penyaringan baris, dan groupby membantu analisis tabel. Periksa tipe data setelah membaca file.|Baca CSV penjualan, periksa dtypes, saring satu wilayah, dan hitung total bulanan.
Data Cleaning|Nilai hilang, duplikasi, dan format tidak konsisten perlu keputusan sesuai konteks. Mengisi semua nilai hilang dengan nol dapat mengubah makna data.|Pisahkan tanggal invalid, tandai duplikasi berdasarkan ID transaksi, dan tulis alasan setiap perubahan.
Exploratory Data Analysis|EDA mencari pola dan masalah data sebelum pemodelan. Distribusi, perbandingan kelompok, serta korelasi menghasilkan hipotesis yang masih perlu diuji.|Bandingkan jumlah transaksi, median nilai, dan proporsi data hilang antarwilayah; tulis tiga pertanyaan lanjutan.
Data Visualization|Visualisasi memerlukan pemilihan grafik sesuai pertanyaan. Label dan satuan harus eksplisit, dan warna tidak boleh menjadi satu-satunya pembeda informasi.|Buat grafik tren bulanan dan batang per kategori, lalu tambahkan judul yang menyatakan periode serta ukuran.
Data Analytics Project|Analisis yang dapat diulang memisahkan data mentah, pembersihan, perhitungan, dan interpretasi. Kesimpulan harus membedakan pengamatan dari dugaan penyebab.|Serahkan notebook dengan pertanyaan bisnis, pemeriksaan kualitas data, tiga grafik, temuan, serta keterbatasan.
LESSONS,
'C07' => <<<'LESSONS'
Introduction to Business Intelligence|Business intelligence menghubungkan data operasional dengan informasi untuk pemantauan keputusan. Definisi indikator harus disepakati agar dua laporan tidak menyebut angka berbeda sebagai metrik yang sama.|Definisikan penjualan bersih, periode, sumber, dan perlakuan retur untuk satu laporan.
Power BI Ecosystem|Power BI Desktop dipakai untuk menyiapkan model dan laporan; layanan Power BI mendukung publikasi dan berbagi. Hak akses dan refresh perlu direncanakan terpisah dari desain visual.|Gambarkan alur sumber data, Desktop, publikasi, refresh, dan pembaca laporan.
Connecting Data Sources|Koneksi data memerlukan pilihan mode penyimpanan dan kredensial yang sesuai. Akses sumber harus dibatasi. Periksa tipe kolom serta waktu pembaruan sebelum membuat visual.|Hubungkan file latihan dan dokumentasikan lokasi sumber, tipe kolom, serta cara memperbaruinya.
Power Query|Langkah Power Query mendeskripsikan transformasi yang dapat diulang. Filter dan pemilihan kolom sedini mungkin dapat mengurangi data yang diproses, tergantung sumber dan query folding.|Gabungkan file bulanan dengan struktur sama dan pastikan langkah tetap berhasil pada file bulan berikutnya.
Data Transformation|Transformasi mengubah struktur dan kualitas data agar cocok dengan model. Unpivot dapat mengubah kolom bulan menjadi pasangan bulan dan nilai.|Unpivot tabel Januari–Desember menjadi baris transaksi per bulan; cocokkan total sebelum dan sesudah.
Data Modeling & Relationships|Tabel fakta menyimpan peristiwa terukur, dimensi memberi konteks. Relationship meneruskan filter sesuai arah dan kardinalitas. Relasi ambigu dapat menghasilkan total yang salah.|Rancang fakta penjualan dengan dimensi produk dan tanggal; jelaskan sisi satu dan banyak.
DAX Fundamentals|Measure DAX dihitung mengikuti konteks filter. Calculated column disimpan per baris saat pemrosesan model. Pilih measure untuk agregasi yang perlu berubah sesuai filter.|Buat measure total penjualan dan amati perubahan hasil ketika filter wilayah diterapkan.
Data Visualization|Grafik harus menjawab pertanyaan, bukan sekadar menunjukkan fitur. Penggunaan sumbu, urutan kategori, dan format angka memengaruhi keterbacaan.|Buat visual perbandingan wilayah dan tren waktu; hilangkan elemen yang tidak membantu membaca nilai.
Dashboard Design|Susunan dashboard mengikuti urutan keputusan pengguna. Tempatkan indikator utama dekat konteks periode dan filter. Cantumkan waktu pembaruan agar pembaca memahami kesegaran data.|Susun satu halaman dengan KPI, tren, rincian, serta filter yang jelas; uji dengan dua pertanyaan pengguna.
End-to-End BI Dashboard Project|Proyek BI mencakup definisi metrik, transformasi, model, visual, serta verifikasi. Visual menarik tidak menggantikan pemeriksaan angka dengan sumber.|Buat laporan penjualan dengan model bintang, tiga measure, dan bukti rekonsiliasi total terhadap data mentah.
LESSONS,
'C08' => <<<'LESSONS'
Introduction to Data Engineering|Data engineering menyiapkan data agar tersedia, konsisten, dan dapat digunakan. Pipeline mencakup ekstraksi, transformasi, penyimpanan, serta pemantauan kegagalan.|Gambarkan perjalanan data pesanan dari API sampai tabel analitik dan sebutkan titik kegagalannya.
Advanced SQL|SQL analitik menggabungkan join, agregasi, CTE, dan window function. Tentukan grain atau unit baris sebelum menggabungkan data agar hitungan tidak berlipat.|Hitung transaksi terbaru per pelanggan dan cocokkan jumlah hasil dengan jumlah pelanggan unik.
Data Modeling|Model data harus menjelaskan unit baris, kunci, hubungan, dan perubahan historis. Grain penjualan per item berbeda dari grain per pesanan.|Rancang fakta item pesanan dan jelaskan bagaimana menghitung jumlah pesanan tanpa menghitung item sebagai pesanan.
ETL vs ELT|ETL mentransformasi data sebelum dimuat ke tujuan; ELT memuat dahulu lalu mentransformasi di tujuan. Pilihan bergantung kapasitas sistem, pengendalian data, dan kebutuhan pemrosesan.|Bandingkan ETL dan ELT untuk file besar dengan kolom sensitif; jelaskan tempat pembatasan akses dilakukan.
Python Data Pipeline|Pipeline perlu validasi input, logging, penanganan kegagalan, dan idempotensi. Menjalankan ulang batch yang sama seharusnya tidak menambah duplikasi.|Buat proses CSV ke tabel latihan dengan batch ID dan pemeriksaan jumlah baris sebelum commit.
Working with APIs|API dapat memakai pagination, rate limit, dan autentikasi. Retry perlu mempertimbangkan sifat operasi agar tidak menggandakan perubahan.|Rancang pengambilan semua halaman API dengan pencatatan cursor terakhir dan penanganan respons 429.
Data Warehouse|Warehouse menyimpan data terstruktur untuk analitik lintas sumber. Definisi dimensi dan fakta yang konsisten membantu membandingkan metrik antardepartemen.|Rancang dimensi pelanggan, produk, dan tanggal untuk fakta transaksi beserta aturan pembaruannya.
Data Lake|Data lake menampung data dengan berbagai format. Penyimpanan fleksibel tetap membutuhkan katalog, hak akses, kualitas, dan kebijakan retensi.|Pisahkan zona raw dan curated; jelaskan siapa yang boleh mengubah masing-masing zona.
Data Pipeline Orchestration|Orkestrasi mengatur dependensi, jadwal, retry, dan pemantauan pekerjaan. Selesainya satu task harus memiliki kriteria yang bisa diverifikasi sebelum task berikutnya berjalan.|Buat DAG ekstraksi, validasi, transformasi, dan publikasi; tentukan tindakan ketika validasi gagal.
Data Engineering Project|Pipeline siap ditinjau memiliki sumber, skema tujuan, aturan kualitas, serta prosedur pemulihan. Uji pengulangan batch dan input rusak.|Bangun pipeline dua sumber ke tabel analitik; sertakan log, pemeriksaan duplikasi, dan hasil pengujian retry.
LESSONS,
'C09' => <<<'LESSONS'
Introduction to Machine Learning|Machine learning mempelajari pola dari data untuk tujuan tertentu. Supervised learning memakai target, sedangkan unsupervised learning mencari struktur tanpa target tersebut.|Tentukan apakah prediksi jumlah penjualan dan segmentasi pelanggan termasuk supervised atau unsupervised.
Machine Learning Workflow|Tentukan masalah, data, baseline, pembagian data, model, evaluasi, dan pemantauan. Data test harus tetap terpisah dari keputusan pelatihan agar evaluasi tidak terlalu optimistis.|Rancang pembagian data berdasarkan waktu untuk prediksi penjualan bulan berikutnya.
Data Preprocessing|Transformasi seperti imputasi dan scaling harus dipelajari dari data training, lalu diterapkan ke validation/test. Memakai seluruh data sebelum split dapat menyebabkan kebocoran.|Susun pipeline imputasi dan scaling tanpa melihat statistik data test.
Linear Regression|Regresi linear memprediksi nilai numerik dari kombinasi prediktor. Interpretasi koefisien bergantung satuan dan variabel lain dalam model.|Bandingkan prediksi model harga dengan baseline rata-rata menggunakan MAE pada data terpisah.
Classification|Klasifikasi memprediksi kelas. Threshold mengubah keseimbangan false positive dan false negative. Akurasi dapat menyesatkan jika kelas tidak seimbang.|Untuk deteksi keluhan mendesak, jelaskan konsekuensi salah melewatkan kasus dibanding salah memberi alarm.
Decision Tree & Ensemble|Decision tree membagi data berdasarkan aturan fitur. Pohon terlalu dalam dapat overfit. Ensemble menggabungkan model dengan cara tertentu untuk memperbaiki kemampuan generalisasi.|Bandingkan pohon dangkal dan dalam pada train serta validation; jelaskan tanda overfitting.
Clustering|Clustering mengelompokkan kemiripan berdasarkan fitur dan ukuran jarak. Kelompok yang terbentuk bukan otomatis kategori bisnis yang bermakna.|Coba dua jumlah cluster pelanggan dan periksa apakah profil kelompok dapat dijelaskan tanpa memakai label target.
Model Evaluation|Evaluasi harus mengikuti tujuan dan biaya kesalahan. Precision, recall, MAE, dan metrik lain menjawab pertanyaan berbeda. Gunakan data yang tidak dipakai melatih model.|Buat confusion matrix dan hitung precision serta recall untuk kelas positif.
Feature Engineering & Explainability|Fitur perlu tersedia saat prediksi nyata dilakukan. Penjelasan model membantu memahami kontribusi fitur, tetapi tidak membuktikan hubungan sebab akibat.|Temukan satu fitur yang bocor dari masa depan dan satu fitur yang sah pada prediksi keterlambatan pengiriman.
Machine Learning Project|Proyek harus menunjukkan baseline, split yang tepat, metrik, analisis kesalahan, dan keterbatasan. Skor tinggi tanpa pemisahan data bukan bukti generalisasi.|Serahkan model sederhana dengan evaluasi test, contoh kegagalan, serta rencana pemantauan pergeseran data.
LESSONS,
'C10' => <<<'LESSONS'
Introduction to Business Analysis|Analisis bisnis menghubungkan kebutuhan, perubahan, dan nilai yang diharapkan. Permintaan fitur adalah usulan solusi; analis perlu memahami masalah di belakangnya.|Ubah permintaan “buat dashboard” menjadi masalah, pengguna, keputusan, dan ukuran hasil.
Stakeholder Analysis|Stakeholder memiliki kepentingan, pengaruh, dan kebutuhan informasi yang berbeda. Orang yang menyetujui anggaran belum tentu pengguna utama sistem.|Petakan pengguna, sponsor, operator, dan pihak terdampak pada sistem jadwal kuliah.
Requirement Elicitation|Wawancara, observasi, analisis dokumen, dan workshop menghasilkan jenis informasi berbeda. Pertanyaan terbuka membantu menemukan pekerjaan nyata sebelum mengonfirmasi kebutuhan spesifik.|Susun lima pertanyaan wawancara tentang kendala peminjaman ruang tanpa langsung menawarkan fitur.
Functional & Non-Functional Requirements|Kebutuhan fungsional menjelaskan kemampuan sistem. Kebutuhan nonfungsional menjelaskan kualitas atau batasannya. Keduanya perlu cukup spesifik untuk diuji.|Tulis satu kebutuhan pencarian jadwal dan satu kebutuhan waktu respons beserta kondisi pengujiannya.
User Stories|User story merangkum pengguna, kebutuhan, dan manfaat. Story membantu percakapan, tetapi bukan pengganti detail aturan atau acceptance criteria.|Tulis story pemesanan ruang dan jelaskan aturan bentrok jadwal yang harus dibahas.
Use Cases|Use case menjelaskan interaksi aktor dan sistem untuk mencapai tujuan. Sertakan prasyarat, alur utama, alternatif, dan hasil akhir.|Dokumentasikan peminjaman buku termasuk kondisi stok habis dan batas pinjaman terlampaui.
Acceptance Criteria|Acceptance criteria menjelaskan kondisi yang harus terpenuhi agar pekerjaan diterima. Kriteria seperti “mudah digunakan” perlu ukuran atau skenario yang dapat diperiksa.|Tulis Given-When-Then untuk penolakan pemesanan ruang pada waktu yang sudah dipakai.
Gap Analysis & Root Cause Analysis|Gap membandingkan kondisi saat ini dengan yang dituju. Root cause analysis menguji alasan masalah terjadi; gejala dan dugaan penyebab tidak boleh dianggap sama.|Analisis keterlambatan persetujuan menggunakan bukti waktu tunggu dan tiga kemungkinan penyebab.
Requirement Prioritization|Prioritas mempertimbangkan nilai, risiko, biaya, dependensi, dan kewajiban. Label semua kebutuhan sebagai wajib membuat urutan kerja tidak berguna.|Urutkan lima kebutuhan layanan kampus dan jelaskan trade-off jika kapasitas hanya cukup untuk dua.
Business Analysis Case Study|Hasil analisis yang bisa ditinjau menghubungkan masalah, bukti, kebutuhan, kriteria penerimaan, dan keputusan prioritas.|Buat dokumen pengadaan kampus dengan stakeholder, AS-IS, lima kebutuhan teruji, dan ruang lingkup yang dikecualikan.
LESSONS,
'C11' => <<<'LESSONS'
System Development Life Cycle|SDLC mengorganisasi pekerjaan analisis, perancangan, implementasi, pengujian, dan pemeliharaan. Tahapan dapat berulang; umpan balik perlu mengalir ke keputusan sebelumnya.|Petakan artefak yang dihasilkan pada tiap tahap pengembangan sistem peminjaman ruang.
Feasibility Study|Kelayakan menilai aspek teknis, operasional, biaya, waktu, dan batasan organisasi. Solusi yang mungkin secara teknis belum tentu layak dijalankan.|Bandingkan membangun aplikasi sendiri dan memakai layanan tersedia berdasarkan biaya serta kemampuan tim.
Requirement Analysis|Analisis kebutuhan memeriksa konsistensi, kelengkapan, konflik, dan keterujian permintaan. Kebutuhan harus dapat ditelusuri ke tujuan atau stakeholder.|Temukan konflik antara “semua data terbuka” dan “identitas mahasiswa hanya untuk petugas”.
Use Case Diagram|Diagram use case menunjukkan aktor dan tujuan interaksi pada batas sistem. Diagram ini tidak menggambarkan urutan langkah secara rinci.|Gambar aktor mahasiswa dan petugas dengan use case meminjam, mengembalikan, dan mengelola koleksi.
Activity Diagram|Activity diagram menggambarkan alur kerja, keputusan, serta pekerjaan paralel. Guard condition perlu menjelaskan kapan cabang dipilih.|Gambarkan alur permohonan dengan keputusan lengkap/tidak lengkap dan dua pemeriksaan paralel.
Sequence Diagram|Sequence diagram menunjukkan urutan pesan antarpartisipan sepanjang waktu. Bedakan request, respons, dan kemungkinan kegagalan.|Gambar interaksi browser, controller, dan database saat menyimpan peminjaman yang valid.
Class Diagram|Class diagram menunjukkan struktur tipe, atribut, operasi, dan hubungan. Multiplicity menjelaskan jumlah objek yang dapat berhubungan.|Modelkan Buku, Eksemplar, Anggota, dan Peminjaman beserta multiplicity yang tepat.
Entity Relationship Diagram|ERD menjelaskan entitas, atribut, kunci, dan relasi data. Relasi banyak-ke-banyak biasanya membutuhkan entitas penghubung pada model relasional.|Rancang mahasiswa, kelas, dan keikutsertaan; tentukan tempat penyimpanan nilai akhir.
System Architecture Fundamentals|Arsitektur menjelaskan pembagian tanggung jawab dan hubungan komponen. Kebutuhan kualitas seperti keamanan dan ketersediaan memengaruhi pilihan struktur.|Gambarkan frontend, backend, database, dan penyimpanan berkas beserta batas kepercayaan.
System Design Project|Desain perlu konsisten dari kebutuhan sampai diagram dan skema data. Jelaskan keputusan serta alternatif yang ditolak, bukan hanya menggambar komponen.|Serahkan use case, sequence diagram, ERD, dan dua keputusan arsitektur untuk layanan peminjaman.
LESSONS,
'C12' => <<<'LESSONS'
Product Management Fundamentals|Manajemen produk menghubungkan masalah pengguna, tujuan organisasi, dan pilihan pengembangan. Output fitur berbeda dari outcome perubahan perilaku atau hasil.|Bedakan output “fitur pengingat” dan outcome “pengurangan keterlambatan pengembalian”.
Product Discovery|Discovery menguji asumsi tentang kebutuhan, manfaat, kelayakan, dan risiko sebelum membangun penuh. Wawancara tidak otomatis membuktikan pengguna akan memakai produk.|Tuliskan asumsi paling berisiko pada aplikasi antrean dan eksperimen murah untuk mengujinya.
Customer Problem Identification|Masalah pengguna perlu konteks, frekuensi, dampak, dan cara penyelesaian saat ini. Pernyataan solusi dapat menyembunyikan kebutuhan yang sebenarnya.|Ubah “butuh chatbot” menjadi deskripsi kendala layanan yang dapat diamati.
Value Proposition|Proposisi nilai menjelaskan manfaat bagi kelompok pengguna tertentu dibanding alternatif yang mereka pakai. Klaim harus terkait masalah nyata.|Tulis manfaat layanan reservasi ruang bagi mahasiswa dan bedakan dari manfaat bagi pengelola.
Product Requirement Document|PRD merangkum tujuan, pengguna, ruang lingkup, perilaku, ukuran keberhasilan, dan batasan. Detail implementasi boleh menyertai, tetapi tidak menggantikan alasan produk.|Buat PRD singkat pengingat pinjaman dengan kriteria keberhasilan dan hal yang tidak dikerjakan.
Product Roadmap|Roadmap mengomunikasikan arah dan urutan prioritas. Tingkat kepastian biasanya menurun untuk rencana yang semakin jauh. Roadmap bukan janji semua fitur selesai pada tanggal tetap.|Susun tiga horizon pekerjaan dengan outcome, dependensi, dan asumsi yang perlu diuji.
Prioritization Framework|Kerangka prioritas membantu membandingkan alternatif, tetapi skor tergantung kualitas asumsi. Dampak besar yang tidak didukung bukti perlu tingkat keyakinan rendah.|Bandingkan tiga ide dengan dampak, usaha, dan keyakinan; jelaskan keputusan yang berubah bila asumsi salah.
Product Metrics & Experimentation|Metrik harus terkait tujuan, memiliki definisi, dan memperhatikan efek samping. Eksperimen membutuhkan kelompok pembanding dan ukuran hasil yang ditetapkan lebih dahulu.|Rancang uji pengingat pinjaman dengan metrik keterlambatan dan guardrail keluhan notifikasi.
LESSONS,
'C13' => <<<'LESSONS'
Project Management Fundamentals|Proyek memiliki tujuan, batas waktu, sumber daya, dan kriteria selesai. Menambah ruang lingkup dapat memengaruhi biaya dan jadwal.|Tulis project charter singkat untuk penerapan sistem inventaris laboratorium.
Project Scope & WBS|Scope menentukan hasil yang termasuk dan tidak termasuk proyek. WBS menguraikan pekerjaan atau deliverable agar estimasi serta tanggung jawab dapat dikelola.|Uraikan proyek inventaris menjadi deliverable dan paket kerja yang dapat diverifikasi.
Scheduling|Jadwal memperhitungkan durasi dan dependensi. Critical path menentukan rangkaian yang membatasi waktu selesai berdasarkan asumsi model.|Buat jaringan lima pekerjaan, tentukan dependensi, dan hitung pengaruh keterlambatan satu aktivitas.
Resource & Cost Management|Estimasi biaya perlu menjelaskan orang, perangkat, layanan, serta cadangan untuk ketidakpastian. Kapasitas tim tidak sama dengan jumlah jam kalender.|Estimasi biaya proyek kecil dan tuliskan asumsi tarif, kapasitas, serta biaya berulang.
Risk Management|Risiko adalah kejadian yang belum pasti; isu sudah terjadi. Penanganan membutuhkan pemilik, dampak, kemungkinan, dan respons yang dapat dilaksanakan.|Buat risk register untuk keterlambatan integrasi, kehilangan anggota tim, dan perubahan kebutuhan.
Agile Fundamentals|Pendekatan agile menggunakan umpan balik dan pengiriman bertahap untuk menyesuaikan pekerjaan. Fleksibilitas tidak berarti tidak ada rencana atau dokumentasi.|Pecah sistem reservasi menjadi increment yang bisa diuji pengguna tanpa menunggu semua fitur selesai.
Scrum & Kanban|Scrum mengatur pekerjaan melalui akuntabilitas, event, dan artefak. Kanban memvisualisasikan aliran serta membatasi pekerjaan berjalan. Keduanya perlu inspeksi hambatan nyata.|Buat papan kerja dengan batas WIP dan jelaskan tindakan saat kolom pengujian menumpuk.
Agile Project Simulation|Simulasi perlu backlog, tujuan pendek, definisi selesai, serta umpan balik. Ukur penyelesaian hasil, bukan hanya kesibukan anggota.|Jalankan simulasi dua iterasi, catat perubahan prioritas, dan tulis satu perbaikan proses berdasarkan observasi.
LESSONS,
'C14' => <<<'LESSONS'
Programming Logic|Algoritma adalah urutan langkah untuk menyelesaikan masalah dengan kondisi yang jelas. Contoh masukan dan keluaran membantu memeriksa logika sebelum menulis kode.|Tulis pseudocode menghitung denda dengan batas maksimum dan uji tiga kasus batas.
Variables & Data Types|Tipe data menentukan operasi yang bermakna. Angka, teks, boolean, dan nilai kosong memiliki perilaku berbeda. Konversi tipe perlu memperhatikan input invalid.|Validasi masukan usia yang dapat berupa angka, kosong, atau teks tidak numerik.
Conditional Statements|Percabangan menjalankan jalur berdasarkan kondisi. Urutan kondisi yang saling tumpang tindih dapat mengubah hasil.|Implementasikan kategori nilai dan uji angka tepat pada setiap batas kategori.
Loops|Loop mengulang pekerjaan sampai kondisi terpenuhi atau koleksi habis. Batas awal/akhir yang salah dapat melewatkan atau menggandakan elemen.|Hitung jumlah angka genap dalam daftar, termasuk daftar kosong dan satu elemen.
Functions|Fungsi membungkus satu tanggung jawab dengan input dan output yang jelas. Efek samping perlu diketahui agar perilakunya mudah diuji.|Pisahkan validasi, perhitungan, dan pencetakan hasil dalam program total belanja.
Data Structures|Struktur data dipilih berdasarkan akses, pencarian, urutan, serta perubahan yang dibutuhkan. Map memudahkan pencarian berbasis kunci, sedangkan list menjaga urutan elemen.|Bandingkan list dan map untuk mencari mahasiswa berdasarkan NIM.
Object-Oriented Programming|Objek menggabungkan state dan perilaku. Enkapsulasi menjaga aturan internal melalui operasi yang disediakan. Pewarisan perlu hubungan yang tepat, bukan sekadar reuse kode.|Rancang objek RekeningLatihan dengan metode setor dan tarik yang menolak saldo negatif.
Error Handling|Penanganan error membedakan kegagalan yang dapat dipulihkan dari yang perlu dilaporkan. Jangan menelan exception tanpa informasi karena penyebab hilang.|Tangani file tidak ditemukan dan isi invalid dengan pesan yang berbeda serta tanpa mengekspos data sensitif.
Git & Version Control|Git mencatat snapshot perubahan. Commit kecil dengan tujuan jelas membantu peninjauan dan pemulihan. Branch memisahkan pekerjaan sebelum digabung.|Buat branch latihan, dua commit, dan merge; jelaskan perbedaan working tree, staging area, dan commit.
Programming Project|Program yang dapat ditinjau memiliki cara menjalankan, kasus uji, serta batas input. Keberhasilan pada satu contoh belum cukup.|Bangun aplikasi inventaris sederhana dengan validasi input, pencarian, dan test untuk data kosong serta duplikat.
LESSONS,
'C15' => <<<'LESSONS'
How The Web Works|Browser meminta sumber melalui jaringan dan merender respons. DNS membantu menemukan alamat server, HTTP membawa request/response, dan TLS melindungi komunikasi HTTPS.|Gambarkan perjalanan saat pengguna membuka halaman login, dari URL sampai HTML tampil.
HTML|HTML memberi struktur dan makna konten. Heading, link, button, form, dan label memiliki peran berbeda; elemen semantik membantu aksesibilitas.|Buat formulir login dengan label yang terhubung ke input dan tombol submit native.
CSS|CSS mengatur presentasi melalui cascade, specificity, dan inheritance. Box model menjelaskan content, padding, border, dan margin.|Buat card dengan padding 24px dan tombol berkontras; jelaskan aturan yang menang saat dua selector bertentangan.
JavaScript Fundamentals|JavaScript menangani data dan interaksi. Event listener memisahkan respons pengguna dari markup. Operasi asynchronous perlu penanganan sukses serta gagal.|Buat filter daftar yang tetap menampilkan pesan ketika hasil kosong.
HTTP & Client-Server Architecture|Request memiliki metode, URL, header, dan mungkin body. Status respons mengomunikasikan hasil. GET sebaiknya tidak melakukan perubahan bisnis yang disengaja.|Petakan membaca profil ke GET dan menyimpan perubahan ke POST/PATCH beserta respons invalid.
Backend & MVC|MVC memisahkan data, pengaturan request, dan presentasi. Validasi serta otorisasi harus dilakukan server meskipun browser sudah memeriksa input.|Jelaskan alur route, controller, service, dan view saat mahasiswa mengirim assessment.
REST API|API berbasis resource menggunakan kontrak request dan response yang konsisten. Idempotensi membantu retry aman pada operasi tertentu; pagination membatasi ukuran hasil.|Rancang endpoint daftar kelas dan detail kelas dengan parameter halaman serta struktur error.
Authentication & Authorization|Autentikasi menentukan siapa pengguna; otorisasi menentukan aksi yang diizinkan. Mengetahui ID resource tidak berarti berhak mengaksesnya.|Tuliskan pemeriksaan agar mahasiswa hanya membuka hasil assessment miliknya sendiri.
Database Integration|Query terparameterisasi memisahkan data input dari sintaks SQL. Transaksi menjaga perubahan terkait tetap konsisten ketika satu langkah gagal.|Rancang transaksi menyimpan jawaban dan memperbarui status assessment; jelaskan kapan rollback diperlukan.
Fullstack Application Project|Aplikasi lengkap membutuhkan validasi, otorisasi, error state, dan test selain tampilan. Data pengguna tidak boleh dipercaya hanya karena berasal dari form sendiri.|Bangun CRUD catatan belajar dengan kepemilikan pengguna, pagination, dan test akses akun lain.
LESSONS,
'C16' => <<<'LESSONS'
Software Quality Fundamentals|Kualitas mencakup kesesuaian fungsi dan kebutuhan pengguna, bukan hanya tidak ada crash. Atribut seperti reliabilitas, keamanan, dan kemudahan penggunaan perlu kriteria.|Tetapkan tiga kriteria kualitas terukur untuk halaman assessment.
Software Testing Lifecycle|Pengujian mencakup analisis risiko, desain kasus, persiapan data, eksekusi, dan pelaporan. Aktivitas pengujian dapat berjalan sejak kebutuhan dibahas.|Susun rencana pengujian login dari validasi kebutuhan sampai regression test.
Test Scenario & Test Case|Skenario menyatakan situasi yang diuji; test case menambahkan prasyarat, langkah, input, dan hasil yang diharapkan. Kasus batas sering mengungkap kesalahan.|Tulis kasus jawaban lengkap, belum lengkap, dan attempt milik mahasiswa lain.
Bug Reporting|Laporan bug harus dapat direproduksi. Sertakan lingkungan, langkah, hasil aktual, hasil yang diharapkan, dan bukti yang tidak membocorkan informasi sensitif.|Tulis laporan tombol kosong dengan URL, ukuran viewport, screenshot, dan perilaku saat diklik.
API Testing with Postman|Pengujian API memeriksa status, struktur respons, aturan data, dan otorisasi. Respons 200 saja belum membuktikan hasil benar.|Susun request login, simpan draft, dan akses tanpa token; tulis assertion status serta isi yang relevan.
Automation Testing Fundamentals|Test otomatis paling berguna untuk perilaku berulang dan regresi. Test yang bergantung urutan atau waktu acak menjadi sulit dipercaya.|Otomatiskan validasi form dengan data terisolasi dan pastikan test dapat dijalankan sendiri.
Performance & Security Testing Introduction|Pengujian performa membutuhkan beban, metrik, dan lingkungan yang jelas. Pengujian keamanan hanya dilakukan pada sistem yang diizinkan, dengan cakupan terkontrol.|Buat rencana uji endpoint milik sendiri yang mengukur latency dan penolakan akses tidak sah tanpa menyerang layanan luar.
QA Testing Project|Laporan kualitas menghubungkan risiko, cakupan test, hasil, dan masalah tersisa. Jangan menyatakan semua fitur aman hanya karena beberapa test lulus.|Uji satu alur belajar end-to-end dan serahkan test case, laporan bug, serta keterbatasan pengujian.
LESSONS,
'C17' => <<<'LESSONS'
Human Centered Design|Desain berpusat pada manusia dimulai dari kebutuhan, konteks, dan evaluasi dengan pengguna. Preferensi visual desainer tidak cukup untuk memastikan tugas mudah dilakukan.|Amati cara mahasiswa memilih kelas dan catat tiga hambatan tanpa langsung mengusulkan UI.
UX Research|Metode riset dipilih berdasarkan pertanyaan. Wawancara menjelaskan pengalaman; observasi menunjukkan perilaku. Sampel kecil dapat memberi wawasan tetapi bukan estimasi populasi yang kuat.|Susun panduan wawancara tentang pengalaman mengerjakan assessment, hindari pertanyaan menggiring.
User Persona|Persona merangkum pola kebutuhan berbasis riset, bukan biografi rekaan yang dianggap fakta. Jika belum ada riset, nyatakan sebagai hipotesis.|Buat profil kebutuhan mahasiswa bekerja dari catatan wawancara; tandai bagian yang masih asumsi.
Customer Journey|Journey memetakan tahap, tindakan, kebutuhan, dan hambatan sepanjang pengalaman. Bukti perlu dibedakan dari interpretasi tim.|Petakan register sampai memilih kelas dan tandai titik saat pengguna membutuhkan penjelasan skor.
Information Architecture|Arsitektur informasi mengatur pengelompokan dan penamaan agar pengguna menemukan tujuan. Istilah teknis internal sering tidak sesuai bahasa pengguna.|Kelompokkan fitur assessment, hasil, kompetensi, dan kelas; uji nama menu dengan dua tugas pencarian.
Wireframing|Wireframe menguji struktur serta prioritas sebelum detail visual. Fokus pada hierarki, alur, dan aksi utama, bukan warna atau ilustrasi.|Buat wireframe assessment dengan soal, pilihan, tracker, status simpan, dan navigasi pada desktop serta mobile.
UI Design with Figma|Komponen dan token membantu konsistensi ukuran, warna, serta state. Auto layout membantu komponen merespons teks panjang dan ukuran layar.|Buat komponen tombol dengan state default, hover, focus, loading, dan disabled; uji label panjang.
Prototype|Prototype mensimulasikan interaksi untuk menguji pemahaman alur. Jelaskan bagian yang benar-benar berfungsi dan bagian yang masih simulasi.|Hubungkan layar daftar, pengerjaan, dan hasil assessment; sediakan alur error serta kembali.
Usability Testing & Accessibility|Usability testing memeriksa keberhasilan tugas, sedangkan pemeriksaan aksesibilitas mencakup keyboard, label, kontras, dan struktur. Warna saja tidak cukup untuk menyampaikan status.|Uji memilih jawaban tanpa mouse, fokus tracker, dan pembacaan status benar/salah tanpa mengandalkan warna.
UI/UX Portfolio Case Study|Studi kasus perlu menunjukkan masalah, bukti, alternatif, keputusan, dan hasil evaluasi. Screenshot akhir saja tidak menjelaskan proses desain.|Susun studi kasus perbaikan assessment dengan temuan awal, rancangan, hasil uji, dan batasan.
LESSONS,
'C18' => <<<'LESSONS'
Computer Hardware & Operating Systems|CPU memproses instruksi, RAM menyimpan data kerja sementara, dan storage mempertahankan data. Sistem operasi mengelola proses, memori, perangkat, dan akses.|Jelaskan mengapa penambahan RAM tidak selalu menyelesaikan masalah jaringan lambat.
Network Fundamentals|Jaringan menghubungkan perangkat melalui aturan komunikasi. Bandwidth menggambarkan kapasitas, latency menggambarkan waktu tunda, dan packet loss menggambarkan kehilangan paket.|Bedakan gejala bandwidth rendah, latency tinggi, dan kehilangan paket pada panggilan video.
TCP/IP|IP mengalamatkan dan merutekan paket. TCP menyediakan aliran data andal dengan pengurutan dan retransmisi, sedangkan UDP tidak memberikan jaminan yang sama.|Jelaskan alasan aplikasi streaming dan transfer berkas memiliki kebutuhan transport berbeda.
IP Addressing & Subnetting|Alamat IP dan prefix menentukan bagian jaringan serta host. Subnet membagi ruang alamat untuk pengaturan dan segmentasi. Gateway diperlukan untuk menjangkau jaringan lain.|Untuk jaringan latihan 192.168.10.0/24, tentukan apakah 192.168.10.25 dan 192.168.11.25 berada pada subnet yang sama.
Switching & Routing|Switch umumnya meneruskan frame dalam jaringan lokal berdasarkan MAC, router meneruskan paket antarnetwork berdasarkan rute IP. VLAN memisahkan domain broadcast logis.|Gambar dua VLAN laboratorium yang berkomunikasi melalui router dengan pembatasan akses.
DNS & DHCP|DNS menerjemahkan nama menjadi record seperti alamat IP. DHCP membagikan konfigurasi jaringan seperti alamat, gateway, dan DNS. Kegagalan keduanya menghasilkan gejala berbeda.|Jelaskan langkah diagnosis ketika alamat IP dapat diakses tetapi nama domain tidak.
Linux Fundamentals|Linux mengelola berkas, proses, pengguna, dan permission. Hak minimum mengurangi dampak kesalahan. Jalankan latihan di direktori atau mesin latihan.|Periksa pwd, ls, dan permission berkas; jelaskan perbedaan read, write, execute pada berkas.
Virtualization|Virtualisasi menjalankan mesin dengan sumber daya yang diabstraksikan. VM memiliki sistem operasi sendiri; container berbagi kernel host dalam model umumnya.|Bandingkan VM dan container untuk lingkungan pengujian aplikasi tanpa menganggap isolasinya identik.
Monitoring & Troubleshooting|Diagnosis dimulai dari gejala, cakupan, perubahan terakhir, dan bukti. Ubah satu faktor lalu verifikasi agar penyebab tidak tercampur.|Susun urutan pemeriksaan konektivitas lokal, gateway, DNS, dan layanan aplikasi pada jaringan latihan.
Infrastructure Lab Project|Laboratorium perlu topologi, konfigurasi, dan langkah pemulihan yang tercatat. Hindari perubahan pada jaringan kampus tanpa izin.|Bangun jaringan virtual dua host, dokumentasikan alamat dan konektivitas, lalu simulasikan satu kegagalan DNS.
LESSONS,
'C19' => <<<'LESSONS'
Cloud Computing Fundamentals|Layanan cloud menyediakan sumber daya melalui jaringan dengan pengukuran penggunaan. IaaS, PaaS, dan SaaS membagi tanggung jawab pengelolaan secara berbeda; penggunaan cloud tetap membutuhkan pengendalian biaya.|Bandingkan tanggung jawab pengelolaan server pada IaaS dengan aplikasi SaaS dan tetapkan batas biaya latihan.
Cloud Networking|Subnet, routing, firewall, dan load balancer mengatur jalur komunikasi. Database biasanya tidak perlu menerima koneksi langsung dari internet.|Gambar jalur pengguna ke aplikasi dan database, lalu tandai koneksi yang perlu dibatasi.
Identity & Access Management|Identitas pengguna dan workload memperoleh izin melalui kebijakan. Hak minimum, kredensial berumur pendek, dan pemisahan lingkungan mengurangi dampak kebocoran.|Susun izin layanan yang hanya perlu membaca satu bucket tanpa memberi akses administrator.
Compute & Storage|Compute menjalankan workload; object, block, dan file storage melayani pola penyimpanan berbeda. Pilihan perlu mempertimbangkan akses, durabilitas, kapasitas, dan biaya.|Pilih penyimpanan untuk foto pengguna, disk mesin virtual, dan folder bersama beserta alasannya.
Docker|Image berisi paket aplikasi, container menjalankan instansinya. Data persisten perlu volume atau layanan eksternal; secret tidak semestinya dimasukkan ke image.|Jelaskan apa yang terjadi pada data lokal container saat container diganti dan rancang penyimpanannya.
CI/CD|Continuous integration menjalankan pemeriksaan perubahan secara rutin. Pipeline deployment memerlukan tahapan uji, pengelolaan secret, dan cara kembali ke versi sebelumnya.|Rancang pipeline lint, test, build, staging, persetujuan, lalu deployment untuk aplikasi latihan.
Infrastructure as Code|Konfigurasi infrastruktur yang ditulis sebagai kode dapat ditinjau dan dilacak. State serta kredensial perlu dilindungi; perubahan tetap perlu diperiksa sebelum diterapkan.|Buat rancangan perubahan satu server menjadi dua dengan rencana pemeriksaan dan pembatalan.
Monitoring & Logging|Metrics menunjukkan tren, logs merekam kejadian, dan traces mengikuti permintaan lintas layanan. Alert perlu terkait dampak pengguna agar tidak sekadar menghasilkan kebisingan.|Tentukan alert untuk kenaikan error login beserta bukti yang harus diperiksa sebelum menyimpulkan penyebabnya.
Cloud Security|Keamanan cloud merupakan tanggung jawab bersama yang bergantung pada layanan. Konfigurasi akses, patching yang menjadi kewajiban pelanggan, backup, dan audit tetap perlu direncanakan.|Periksa rancangan aplikasi latihan untuk akses publik yang tidak perlu, secret terbuka, dan prosedur pemulihan.
Cloud Deployment Project|Deployment yang dapat diulang membutuhkan konfigurasi, pengujian kesehatan, observabilitas, dan rollback. Lingkungan latihan perlu batas anggaran dan jadwal penghentian sumber daya.|Dokumentasikan deployment aplikasi sederhana, health check, rollback, dan daftar sumber daya yang perlu dihentikan setelah latihan.
LESSONS,
'C20' => <<<'LESSONS'
Cybersecurity Fundamentals|Keamanan melindungi aset dari ancaman dengan kontrol yang sesuai risiko. Kontrol teknis perlu didukung proses dan perilaku pengguna, bukan hanya pemasangan alat.|Daftar aset aplikasi mahasiswa, ancaman utama, dampak, dan satu kontrol untuk setiap ancaman.
CIA Triad & Security Risk|Confidentiality membatasi pengungkapan, integrity menjaga ketepatan, dan availability menjaga ketersediaan. Risiko mempertimbangkan kemungkinan serta dampak dalam konteks organisasi.|Klasifikasikan kebocoran nilai, perubahan nilai tanpa izin, dan layanan tidak tersedia menurut dampak CIA.
Network Security|Segmentasi dan firewall membatasi komunikasi yang tidak diperlukan. Enkripsi melindungi data dalam transit tetapi tidak menggantikan autentikasi dan otorisasi aplikasi.|Susun aturan akses antara perangkat pengguna, server aplikasi, dan database dengan prinsip deny by default.
Identity & Access Management|Autentikasi membuktikan identitas, otorisasi menentukan tindakan yang diizinkan. Akun bersama menyulitkan audit; MFA mengurangi risiko tertentu tetapi bukan pengganti semua kontrol.|Tentukan proses pemberian, peninjauan, dan pencabutan akses untuk staf yang pindah tugas.
Endpoint Security|Perangkat pengguna membutuhkan pembaruan, pembatasan hak, proteksi malware, dan pengelolaan konfigurasi. Backup terpisah membantu pemulihan namun harus diuji.|Susun checklist perangkat kerja sebelum diizinkan mengakses data sensitif organisasi.
Web Application Security|Validasi input, query berparameter, otorisasi sisi server, dan pengelolaan session menangani kelas risiko berbeda. Menyembunyikan tombol tidak mencegah akses endpoint.|Jelaskan cara mencegah mahasiswa mengakses hasil assessment milik mahasiswa lain melalui perubahan ID URL.
Vulnerability Management|Temuan kerentanan perlu divalidasi, diprioritaskan menurut eksposur dan dampak, diperbaiki, lalu diuji ulang. Pemindaian hanya dilakukan pada sistem yang diizinkan.|Urutkan perbaikan celah login publik dan bug lokal berisiko rendah, sertakan alasan serta verifikasi.
Logging & SIEM|Log keamanan membantu menghubungkan kejadian, tetapi data rahasia seperti password dan token tidak boleh dicatat. Korelasi perlu mempertimbangkan waktu dan kemungkinan false positive.|Tentukan field log untuk kegagalan login berulang tanpa merekam password atau token session.
Incident Response|Respons insiden mencakup persiapan, deteksi, penanganan, pemulihan, dan pembelajaran. Bukti perlu dipertahankan; tindakan tergesa dapat menghapus informasi penting.|Susun langkah awal saat akun diduga diambil alih, termasuk eskalasi dan pencatatan waktu kejadian.
Cybersecurity Investigation Project|Investigasi harus memiliki ruang lingkup, bukti, hipotesis, dan batas kepastian. Latihan menggunakan log sintetis atau lingkungan berizin, bukan menyerang sistem nyata.|Analisis log latihan untuk login mencurigakan dan tulis kronologi, bukti pendukung, serta hipotesis alternatif.
LESSONS,
'C21' => <<<'LESSONS'
IT Governance Fundamentals|Tata kelola menetapkan arah, akuntabilitas, dan pengawasan agar TI mendukung tujuan organisasi. Manajemen melaksanakan kegiatan untuk mencapai arah tersebut.|Bedakan keputusan prioritas investasi TI dengan pekerjaan operasional pemeliharaan server.
IT Risk Management|Risiko TI perlu pemilik, penilaian, respons, dan pemantauan. Menerima risiko merupakan keputusan sadar yang dicatat, bukan mengabaikan temuan.|Susun risk register gangguan layanan pembelajaran dengan dampak, kemungkinan, pemilik, dan respons.
IT Controls|Kontrol preventif mengurangi peluang kejadian, detektif menemukan kejadian, dan korektif mendukung pemulihan. Keberadaan kebijakan belum membuktikan kontrol berjalan.|Petakan pembatasan akses, review log, dan pemulihan backup ke tujuan kontrol serta bukti pelaksanaannya.
COBIT Fundamentals|COBIT adalah kerangka tata kelola dan manajemen informasi serta teknologi organisasi. Penggunaannya perlu disesuaikan dengan tujuan dan konteks, bukan menyalin seluruh praktik tanpa penilaian.|Pilih masalah akuntabilitas layanan TI dan jelaskan informasi yang perlu dikumpulkan sebelum memilih praktik tata kelola.
ISO 27001 Fundamentals|ISO/IEC 27001 membahas persyaratan sistem manajemen keamanan informasi. Penerapannya berbasis risiko dan perbaikan berkelanjutan; satu checklist tidak cukup untuk menyatakan sertifikasi.|Susun ruang lingkup awal pengelolaan keamanan data mahasiswa serta pihak yang bertanggung jawab.
IT Audit Lifecycle|Audit mencakup perencanaan, pengumpulan bukti, evaluasi, pelaporan, dan tindak lanjut. Kesimpulan perlu bertumpu pada bukti yang cukup dan relevan terhadap kriteria.|Rancang pengujian sampel pencabutan akses pegawai keluar dan tentukan dokumen bukti yang diperlukan.
Compliance & Data Privacy|Pengelolaan data pribadi memerlukan tujuan yang jelas, pembatasan akses, retensi, dan penanganan hak subjek sesuai aturan yang berlaku. Kebutuhan hukum harus diverifikasi pada sumber resmi terkini.|Inventarisasi data profil mahasiswa, tujuan pengumpulan, penerima akses, dan usulan masa simpan untuk ditinjau.
IT Audit Case Study|Temuan audit menghubungkan kondisi, kriteria, sebab, dan dampak dengan rekomendasi yang dapat ditindaklanjuti. Keterbatasan sampel perlu dinyatakan.|Tulis temuan akun mantan staf yang masih aktif beserta bukti, risiko, pemilik tindakan, dan cara verifikasi perbaikan.
LESSONS,
'C22' => <<<'LESSONS'
ERP & CRM Fundamentals|ERP mengintegrasikan proses sumber daya organisasi, sedangkan CRM mendukung pengelolaan hubungan pelanggan. Keduanya dapat bertukar data tetapi memiliki fokus yang berbeda.|Petakan pengelolaan stok, pencatatan transaksi, dan tindak lanjut calon pelanggan ke kebutuhan ERP atau CRM.
Enterprise Business Processes|Proses lintas fungsi menghubungkan aktivitas beberapa bagian. Integrasi membutuhkan definisi data, tanggung jawab, dan titik kontrol yang disepakati.|Gambar alur pesanan pelanggan dari penjualan hingga pengiriman dan penagihan.
Master Data|Master data menyimpan entitas inti seperti pelanggan, pemasok, dan produk. Duplikasi serta definisi yang berbeda dapat menghasilkan transaksi dan laporan tidak konsisten.|Rancang aturan identifikasi serta penanganan dua record pelanggan yang ternyata orang yang sama.
Procure-to-Pay|Alur pengadaan hingga pembayaran umumnya melibatkan permintaan, pesanan pembelian, penerimaan, pemeriksaan tagihan, dan pembayaran. Pemisahan tugas mengurangi risiko kesalahan atau penyalahgunaan.|Jelaskan pemeriksaan saat jumlah barang diterima berbeda dari tagihan pemasok.
Order-to-Cash|Alur pesanan hingga penerimaan pembayaran menghubungkan pesanan, pemenuhan, pengiriman, tagihan, dan pembayaran. Status antarbagian harus dapat ditelusuri.|Telusuri penyebab pesanan sudah dikirim tetapi belum tertagih dan identifikasi data penghubungnya.
Finance, Inventory & Operations|Transaksi operasional memengaruhi catatan persediaan dan keuangan. Rekonsiliasi membantu menemukan selisih antara kondisi fisik dan sistem.|Susun langkah pemeriksaan selisih stok tanpa langsung menyesuaikan angka agar terlihat sama.
ERP Integration & Data Migration|Migrasi memerlukan pemetaan field, pembersihan, pengujian, dan rekonsiliasi. Integrasi perlu menangani kegagalan serta duplikasi pengiriman transaksi.|Buat checklist migrasi produk dengan validasi satuan, kode unik, jumlah record, dan rollback.
ERP Implementation Case Study|Implementasi membutuhkan kebutuhan bisnis, konfigurasi, pengujian pengguna, pelatihan, dan dukungan setelah rilis. Perubahan proses sama pentingnya dengan konfigurasi sistem.|Susun rencana pilot pengadaan satu unit organisasi dengan kriteria penerimaan dan penanganan masalah.
LESSONS,
'C23' => <<<'LESSONS'
IT Service Management Fundamentals|Manajemen layanan TI berfokus pada nilai bagi pengguna melalui layanan yang direncanakan dan dikelola. Ukuran teknis perlu dihubungkan dengan kebutuhan pengguna.|Definisikan layanan pembelajaran daring, penggunanya, waktu penting, dan dampak saat layanan gagal.
Service Desk|Service desk menjadi titik kontak untuk pelaporan dan komunikasi. Pencatatan konteks, dampak, dan langkah yang sudah dicoba mempercepat penanganan.|Tulis format tiket masalah login yang cukup jelas untuk ditindaklanjuti tanpa meminta password pengguna.
Incident Management|Penanganan insiden memprioritaskan pemulihan layanan. Prioritas ditentukan oleh dampak dan urgensi, bukan semata siapa yang paling keras meminta.|Bandingkan satu pengguna gagal mencetak dengan seluruh mahasiswa tidak dapat mengirim ujian menjelang batas waktu.
Service Request Management|Permintaan layanan mengikuti prosedur pemenuhan yang telah ditentukan, misalnya permintaan akses. Persetujuan dan verifikasi tetap diperlukan untuk akses sensitif.|Rancang alur permintaan akses aplikasi dengan pemohon, pemberi persetujuan, pelaksana, dan bukti penyelesaian.
Problem Management|Problem management menyelidiki penyebab insiden berulang dan mengurangi dampaknya. Workaround dapat memulihkan layanan tanpa menyelesaikan akar masalah.|Bedakan restart sementara server dengan tindakan mencegah kebocoran memori yang menyebabkan gangguan berulang.
Change Management|Perubahan layanan perlu menilai risiko, dampak, pengujian, jadwal, dan pemulihan. Tingkat kontrol dapat disesuaikan dengan jenis serta risiko perubahan.|Susun rencana perubahan database dengan backup, uji staging, verifikasi, dan kriteria rollback.
SLA & Service Performance|Kesepakatan layanan menetapkan target serta cara pengukuran. Waktu respons berbeda dari waktu penyelesaian dan perlu dijelaskan agar laporan tidak menyesatkan.|Buat definisi waktu respons tiket, jam layanan, pengecualian, dan metode pelaporan bulanan.
IT Service Management Simulation|Simulasi layanan menguji pencatatan, prioritas, eskalasi, komunikasi, dan penutupan. Tiket selesai perlu konfirmasi hasil, bukan hanya status yang diganti.|Simulasikan insiden login massal dari laporan awal sampai konfirmasi pemulihan dan review penyebab.
LESSONS,
'C24' => <<<'LESSONS'
Introduction to Solution Architecture|Arsitektur solusi menghubungkan kebutuhan dengan keputusan struktur sistem. Keputusan perlu mempertimbangkan batasan, atribut kualitas, dan trade-off, bukan hanya memilih teknologi populer.|Daftar batasan biaya, jumlah pengguna, keamanan, dan kemampuan tim untuk aplikasi pembelajaran.
Application Architecture|Komponen aplikasi membagi tanggung jawab dan antarmuka. Pemisahan yang baik memudahkan perubahan; layanan terdistribusi menambah kebutuhan komunikasi serta operasi.|Bandingkan monolit modular dan microservices untuk tim kecil dengan kebutuhan aplikasi sederhana.
Data Architecture|Arsitektur data menjelaskan sumber, penyimpanan, aliran, kepemilikan, dan penggunaan data. Konsistensi serta retensi perlu direncanakan sejak awal.|Gambar aliran jawaban assessment hingga laporan kompetensi, termasuk sumber data yang dianggap otoritatif.
Technology Architecture|Infrastruktur, runtime, jaringan, dan operasi harus mendukung kebutuhan aplikasi. Pilihan teknologi perlu mempertimbangkan dukungan, kemampuan tim, dan biaya total.|Susun rancangan hosting aplikasi beserta backup, pemantauan, dan tanggung jawab operasionalnya.
Integration Architecture|Integrasi memerlukan kontrak data, autentikasi, pengelolaan error, serta aturan pengulangan. Kegagalan sebagian perlu dipertimbangkan agar data tidak diam-diam tidak sinkron.|Rancang respons ketika layanan rekomendasi tidak tersedia tetapi jawaban assessment berhasil disimpan.
API & Event-Driven Architecture|API sinkron memberi respons langsung, sedangkan event menyampaikan kejadian untuk diproses konsumen. Event dapat diterima lebih dari sekali sehingga penanganan duplikasi penting.|Rancang pemrosesan event assessment selesai agar pengiriman ulang tidak menggandakan bukti kompetensi.
Architecture Quality Attributes|Kinerja, keamanan, ketersediaan, kemudahan perubahan, dan aksesibilitas dapat dinyatakan sebagai skenario yang terukur. Peningkatan satu atribut dapat memengaruhi biaya atau atribut lain.|Ubah kebutuhan aplikasi harus cepat menjadi skenario beban, tindakan pengguna, dan target respons yang dapat diuji.
Solution Architecture Case Study|Dokumen arsitektur perlu keputusan, alasan, alternatif, risiko, dan cara evaluasi. Diagram harus menjelaskan hubungan nyata, bukan hanya kumpulan logo teknologi.|Buat rancangan Laravel, PostgreSQL, dan layanan reasoning dengan batas tanggung jawab serta penanganan kegagalan.
LESSONS,
'C25' => <<<'LESSONS'
Professional Communication|Komunikasi kerja yang jelas menyebut konteks, fakta, dampak, dan tindakan yang dibutuhkan. Penyesuaian bahasa membantu audiens mengambil keputusan tanpa kehilangan ketepatan.|Tulis pesan keterlambatan modul yang menjelaskan penyebab terverifikasi, dampak, pilihan, dan kebutuhan keputusan.
Technical Documentation|Dokumentasi teknis menjelaskan tujuan, prasyarat, langkah, hasil yang diharapkan, dan pemulihan kegagalan. Contoh harus dapat dijalankan tanpa membagikan secret.|Susun panduan menjalankan aplikasi lokal dengan konfigurasi contoh dan cara memeriksa keberhasilan koneksi database.
Presentation Skills|Presentasi perlu pesan utama, bukti, dan alur yang sesuai waktu audiens. Visual membantu menjelaskan hubungan yang sulit dijelaskan dengan kalimat saja.|Siapkan presentasi tiga menit tentang alur assessment dan rekomendasi, termasuk satu keterbatasan sistem.
Stakeholder Communication|Pemangku kepentingan membutuhkan informasi dan frekuensi komunikasi berbeda. Risiko serta keputusan perlu dicatat agar kesepahaman dapat diperiksa.|Buat rencana komunikasi perubahan jadwal bagi pengguna, pengembang, dan penanggung jawab proyek.
Team Collaboration|Kolaborasi membutuhkan pembagian tanggung jawab, kesepakatan kerja, dan review. Perbedaan pendapat dibahas melalui tujuan serta bukti, bukan serangan pribadi.|Tulis kesepakatan review kode dan cara menyelesaikan konflik prioritas dua anggota tim.
CV & LinkedIn|Profil karier menyampaikan pengalaman serta keterampilan yang dapat dibuktikan. Klaim perlu sesuai pekerjaan nyata; proyek kuliah tetap bernilai jika kontribusi pribadi dijelaskan.|Ubah daftar teknologi menjadi uraian proyek yang menyebut masalah, kontribusi pribadi, dan hasil yang benar-benar diukur.
Portfolio Development|Portofolio menunjukkan cara berpikir serta hasil kerja. Sertakan konteks, peran, keputusan, bukti, keterbatasan, dan tautan yang dapat diakses tanpa membuka data pribadi.|Susun studi kasus IS-Path dengan alur pengguna, arsitektur, pengujian, dan bagian yang masih perlu validasi.
Technical & Case Interview|Jawaban teknis yang baik memperjelas asumsi, menjelaskan pendekatan, dan memeriksa hasil. Mengakui batas pengetahuan lebih tepat daripada membuat klaim yang tidak dapat dibuktikan.|Latih penjelasan tiga menit tentang perbedaan minat, kompetensi terukur, dan rekomendasi berbasis aturan.
LESSONS,
'C26' => <<<'LESSONS'
AI Fundamentals|AI mencakup pendekatan untuk tugas seperti prediksi, klasifikasi, dan pengambilan keputusan. Aturan eksplisit berbeda dari model yang belajar dari data; pemilihannya mengikuti kebutuhan masalah.|Bedakan rekomendasi berbasis aturan ontologi dengan klasifikasi yang dilatih dari data historis.
Generative AI & LLM Fundamentals|Model bahasa menghasilkan token berdasarkan pola yang dipelajari dan konteks. Keluaran dapat keliru meskipun terdengar meyakinkan, sehingga verifikasi diperlukan pada penggunaan penting.|Tentukan bagian ringkasan materi yang harus diperiksa terhadap sumber sebelum ditampilkan kepada mahasiswa.
Prompt Engineering|Instruksi yang jelas menyebut tugas, konteks, batasan, dan format hasil. Contoh dapat membantu konsistensi tetapi prompt bukan jaminan kebenaran atau pengamanan akses.|Tulis prompt peringkas modul yang membatasi jawaban pada sumber dan meminta penandaan informasi yang tidak tersedia.
AI API Fundamentals|Integrasi API perlu autentikasi, timeout, penanganan batas penggunaan, serta validasi keluaran. Secret disimpan di server dan data pribadi dikirim hanya jika diperlukan serta diizinkan.|Rancang respons aplikasi saat layanan AI timeout tanpa membocorkan API key atau menghilangkan pekerjaan pengguna.
Business Process Automation|Otomasi cocok untuk langkah yang aturannya cukup jelas dan hasilnya dapat diverifikasi. Pengecualian serta tanggung jawab manusia tetap perlu dirancang.|Pilih satu proses administrasi berulang, petakan input, aturan, pengecualian, dan kondisi yang memerlukan pemeriksaan manusia.
RPA / Workflow Automation|RPA mengoperasikan antarmuka, sedangkan workflow dapat menghubungkan layanan melalui API. Perubahan antarmuka, pengulangan, dan kegagalan sebagian perlu ditangani.|Bandingkan otomasi ekspor laporan melalui klik layar dengan API, termasuk risiko perubahan antarmuka dan duplikasi.
AI Governance & Responsible AI|Pengelolaan AI perlu memperhatikan dampak, kualitas data, privasi, bias, pemantauan, dan akuntabilitas. Rekomendasi karier tidak semestinya diperlakukan sebagai keputusan mutlak tentang kemampuan seseorang.|Daftar risiko saran karier yang terlalu pasti dan tulis penjelasan batasan serta mekanisme koreksi pengguna.
AI Business Automation Project|Proyek otomasi perlu baseline, kriteria keberhasilan, uji kegagalan, dan evaluasi dampak. Penghematan waktu tidak boleh diklaim tanpa pengukuran.|Rancang pilot ringkasan tiket dengan data latihan, review manusia, pengukuran kesalahan, dan kondisi penghentian pilot.
LESSONS,
];
