<?php

namespace App\Domains\Assessment\Services;

final class RoleQuestionBank
{
    public function for(string $competency): array
    {
        $questions = [
            'SQL' => ['Laporan pesanan menampilkan pelanggan berulang. Query mana yang paling tepat untuk menghitung jumlah pesanan per pelanggan?', ['a'=>'SELECT customer_id, COUNT(*) FROM orders GROUP BY customer_id','b'=>'SELECT DISTINCT COUNT(customer_id) FROM orders','c'=>'SELECT customer_id FROM orders ORDER BY COUNT(*)','d'=>'UPDATE orders SET customer_id = COUNT(*)'], 'a', 'Agregasi per pelanggan memerlukan COUNT dan GROUP BY customer_id.'],
            'Excel' => ['Dua tabel memiliki kode produk yang sama. Fitur mana yang tepat untuk mengambil kategori dari tabel referensi?', ['a'=>'Conditional Formatting','b'=>'XLOOKUP','c'=>'Goal Seek','d'=>'Text to Columns'], 'b', 'XLOOKUP mengambil nilai terkait berdasarkan kunci pencarian.'],
            'Statistics' => ['Rata-rata durasi transaksi naik tajam karena satu transaksi ekstrem. Ukuran pusat mana yang lebih tahan terhadap pencilan?', ['a'=>'Median','b'=>'Varians','c'=>'Range','d'=>'Jumlah sampel'], 'a', 'Median lebih tahan terhadap nilai ekstrem dibanding rata-rata.'],
            'Python' => ['DataFrame memiliki nilai kosong pada kolom pendapatan. Langkah awal yang paling tepat adalah...', ['a'=>'Mengisi semuanya dengan nol','b'=>'Menghapus seluruh DataFrame','c'=>'Memeriksa pola dan makna nilai kosong sebelum memilih perlakuan','d'=>'Mengubah nama kolom'], 'c', 'Perlakuan missing value harus mengikuti pola, konteks, dan dampaknya.'],
            'Power BI' => ['Total penjualan harus mengikuti filter tanggal pada report. Komponen yang paling tepat adalah...', ['a'=>'Calculated column statis','b'=>'Measure DAX','c'=>'Nama tabel baru','d'=>'Relationship many-to-many tanpa pemeriksaan'], 'b', 'Measure dihitung dalam filter context report.'],
            'Business Understanding' => ['Permintaan awal adalah membuat dashboard penjualan. Pertanyaan pertama yang paling membantu adalah...', ['a'=>'Warna grafik apa yang disukai','b'=>'Keputusan bisnis apa yang harus didukung dan KPI apa yang dipakai','c'=>'Berapa banyak halaman dashboard','d'=>'Framework apa yang sedang populer'], 'b', 'Tujuan keputusan dan KPI menentukan data serta analisis yang relevan.'],
            'Business Process Analysis' => ['Waktu proses pengembalian barang terlalu lama. Bukti awal yang paling berguna adalah...', ['a'=>'Peta alur, waktu tiap aktivitas, antrean, dan pengecualian','b'=>'Logo unit kerja','c'=>'Daftar seluruh aplikasi organisasi','d'=>'Jumlah halaman SOP'], 'a', 'Data alur dan waktu membantu menemukan bottleneck serta variasi proses.'],
            'Requirement Analysis' => ['Stakeholder meminta sistem yang mudah digunakan. Perbaikan requirement yang paling dapat diuji adalah...', ['a'=>'Sistem harus modern','b'=>'Pengguna baru dapat menyelesaikan pengajuan standar tanpa bantuan dalam lima menit','c'=>'Gunakan teknologi terbaik','d'=>'Tampilan harus menarik'], 'b', 'Requirement yang baik memiliki pengguna, tugas, kondisi, dan ukuran keberhasilan.'],
            'Product Management' => ['Dua fitur bersaing untuk sprint berikutnya. Dasar prioritas yang paling kuat adalah...', ['a'=>'Fitur yang namanya paling menarik','b'=>'Dampak pada tujuan produk, bukti kebutuhan, biaya, dan risiko','c'=>'Fitur yang terakhir diminta','d'=>'Fitur dengan layar terbanyak'], 'b', 'Prioritas produk menghubungkan dampak, bukti, upaya, dan risiko.'],
            'Project Management' => ['Vendor mungkin terlambat mengirim komponen penting. Tindakan yang tepat sebelum keterlambatan terjadi adalah...', ['a'=>'Mencatat risiko, menilai dampak, menetapkan pemilik dan mitigasi','b'=>'Menutup proyek','c'=>'Mencatatnya sebagai isu selesai','d'=>'Menghapus jadwal'], 'a', 'Kejadian potensial dikelola sebagai risiko dengan pemilik dan respons.'],
            'Stakeholder Management' => ['Dua stakeholder memiliki tujuan yang bertentangan. Langkah awal paling tepat adalah...', ['a'=>'Memilih yang jabatannya paling tinggi tanpa analisis','b'=>'Memetakan kepentingan, pengaruh, kebutuhan, dan dampak tiap pilihan','c'=>'Menghindari keduanya','d'=>'Menambah fitur untuk semua permintaan'], 'b', 'Pemetaan stakeholder membuat konflik kebutuhan dan trade-off terlihat.'],
            'BPMN' => ['Proses hanya boleh mengikuti satu dari dua jalur berdasarkan nilai transaksi. Gateway yang paling sesuai adalah...', ['a'=>'Parallel gateway','b'=>'Exclusive gateway','c'=>'Start event','d'=>'Message end event'], 'b', 'Exclusive gateway memilih satu jalur berdasarkan kondisi.'],
            'ERP/CRM' => ['Tim menemukan kode pelanggan berbeda untuk pelanggan yang sama di penjualan dan keuangan. Area yang harus dibereskan adalah...', ['a'=>'Master data dan aturan identitas pelanggan','b'=>'Warna laporan','c'=>'Kapasitas RAM pengguna','d'=>'Urutan menu'], 'a', 'Master data yang konsisten diperlukan untuk transaksi dan laporan lintas fungsi.'],
            'Programming & OOP' => ['Objek rekening harus mencegah saldo diubah tanpa validasi. Prinsip OOP yang paling relevan adalah...', ['a'=>'Encapsulation','b'=>'Global variable','c'=>'Copy-paste','d'=>'Infinite loop'], 'a', 'Encapsulation membatasi perubahan state melalui operasi yang tervalidasi.'],
            'Web Development' => ['Form berhasil dikirim tetapi browser mengirim ulang saat halaman dimuat ulang. Pola respons yang membantu adalah...', ['a'=>'Post/Redirect/Get','b'=>'Semua request memakai GET','c'=>'Menyimpan password di URL','d'=>'Menghapus CSRF'], 'a', 'Redirect setelah POST mencegah pengiriman ulang form saat refresh.'],
            'API Development' => ['Client meminta resource yang tidak ada. Respons API yang paling tepat adalah...', ['a'=>'200 dengan data kosong tanpa penjelasan','b'=>'404 dengan format error yang konsisten','c'=>'500 untuk semua kegagalan','d'=>'301 ke halaman login'], 'b', '404 menyatakan resource tidak ditemukan dan body konsisten membantu client.'],
            'Git & Version Control' => ['Perubahan fitur perlu ditinjau sebelum masuk branch utama. Alur yang paling tepat adalah...', ['a'=>'Commit langsung ke semua branch','b'=>'Branch terpisah, commit terarah, lalu pull request dan review','c'=>'Mengirim folder melalui chat','d'=>'Menghapus riwayat'], 'b', 'Branch dan review menjaga perubahan dapat dilacak dan diperiksa.'],
            'Software Testing' => ['Bug hanya muncul ketika session kedaluwarsa saat form dikirim. Test yang paling relevan adalah...', ['a'=>'Menguji status dan pemulihan alur setelah session kedaluwarsa','b'=>'Mengganti warna tombol','c'=>'Menghitung baris kode','d'=>'Menguji halaman lain tanpa login'], 'a', 'Test harus mereproduksi pemicu, respons, dan kondisi pemulihan yang bermasalah.'],
            'UI Design' => ['Tombol hijau tidak terbaca pada kartu hijau. Perbaikan yang tepat adalah...', ['a'=>'Menambah animasi','b'=>'Memilih warna teks dan permukaan dengan kontras yang cukup serta state fokus jelas','c'=>'Memperkecil label','d'=>'Menghapus label'], 'b', 'Kontras dan state fokus membuat kontrol terbaca dan dapat digunakan.'],
            'UX Research' => ['Tim belum tahu mengapa mahasiswa berhenti di assessment. Metode awal yang paling berguna adalah...', ['a'=>'Wawancara dan observasi beberapa mahasiswa saat menjalankan tugas','b'=>'Menambah lebih banyak kartu','c'=>'Mengganti database','d'=>'Membuat asumsi dari satu komentar'], 'a', 'Observasi dan wawancara memberi konteks perilaku serta hambatan pengguna.'],
            'Networking' => ['Server dapat dibuka melalui alamat IP tetapi gagal melalui nama domain. Pemeriksaan pertama yang paling relevan adalah...', ['a'=>'DNS resolution','b'=>'Warna kabel','c'=>'Query database','d'=>'CSS browser'], 'a', 'Akses melalui IP yang berhasil mengarahkan diagnosis awal ke resolusi nama.'],
            'Linux' => ['Aplikasi gagal membaca file konfigurasi setelah permission diubah. Pemeriksaan yang tepat adalah...', ['a'=>'Permission, owner, group, dan user proses aplikasi','b'=>'Resolusi layar','c'=>'Nama branch Git','d'=>'Jumlah tabel'], 'a', 'Akses file Linux ditentukan oleh permission dan identitas proses.'],
            'Cloud Computing' => ['Database produksi seharusnya tidak dapat diakses langsung dari internet. Rancangan yang tepat adalah...', ['a'=>'Private subnet dan aturan jaringan yang hanya menerima koneksi aplikasi','b'=>'Membuka semua port','c'=>'Menaruh password di source code','d'=>'Menghapus backup'], 'a', 'Pembatasan jaringan mengurangi permukaan akses database.'],
            'Cybersecurity' => ['Pengguna mengubah ID URL dan dapat melihat hasil assessment orang lain. Kontrol yang harus diperbaiki adalah...', ['a'=>'Otorisasi kepemilikan pada server','b'=>'Menyembunyikan tombol','c'=>'Mengganti font','d'=>'Memperkecil ID'], 'a', 'Server harus memverifikasi hak pengguna terhadap setiap resource.'],
            'IT Governance' => ['Kebijakan backup tersedia tetapi tidak pernah diuji. Bukti efektivitas kontrol yang paling kuat adalah...', ['a'=>'Dokumen kebijakan saja','b'=>'Hasil uji pemulihan berkala dan tindak lanjut kegagalan','c'=>'Nama aplikasi backup','d'=>'Jumlah rapat'], 'b', 'Pelaksanaan dan hasil uji menunjukkan kontrol bekerja.'],
            'Documentation' => ['Panduan setup gagal saat diikuti anggota baru. Perbaikan yang paling membantu adalah...', ['a'=>'Menambah prasyarat, langkah, hasil yang diharapkan, dan pemulihan error','b'=>'Menghapus pesan error','c'=>'Menambah jargon','d'=>'Menyimpan panduan di chat pribadi'], 'a', 'Dokumentasi operasional harus dapat diikuti dan diverifikasi.'],
            'IT Service Management' => ['Seluruh mahasiswa tidak dapat login menjelang ujian. Prioritas tiket seharusnya ditentukan oleh...', ['a'=>'Dampak dan urgensi layanan','b'=>'Panjang nama pelapor','c'=>'Urutan alfabet','d'=>'Jumlah screenshot'], 'a', 'Dampak luas dan waktu kritis menentukan prioritas tinggi.'],
            'Agile' => ['Tim selesai sprint tetapi masalah koordinasi berulang. Forum yang tepat untuk menetapkan perbaikan cara kerja adalah...', ['a'=>'Sprint retrospective','b'=>'Daily stand-up tanpa batas waktu','c'=>'Product launch','d'=>'Kontrak vendor'], 'a', 'Retrospective mengevaluasi proses dan menghasilkan tindakan perbaikan.'],
            'Collaboration' => ['Dua anggota tim mengedit komponen yang sama dan terjadi konflik. Respons yang paling sehat adalah...', ['a'=>'Menyepakati tujuan, meninjau perubahan bersama, dan mencatat keputusan','b'=>'Menghapus pekerjaan salah satu pihak','c'=>'Menghindari komunikasi','d'=>'Membuat dua versi produksi'], 'a', 'Kolaborasi menyelesaikan konflik melalui tujuan, bukti, dan keputusan bersama.'],
            'Software Architecture' => ['Satu layanan kecil dipecah menjadi banyak microservice dan operasional menjadi sulit. Evaluasi yang tepat adalah...', ['a'=>'Menilai trade-off kompleksitas, skala, kemampuan tim, dan kebutuhan perubahan','b'=>'Menambah service lagi','c'=>'Menghapus monitoring','d'=>'Mengikuti tren terbaru'], 'a', 'Pilihan arsitektur perlu mengikuti kebutuhan dan biaya operasional nyata.'],
            'Solution Architecture' => ['Layanan rekomendasi gagal tetapi jawaban assessment sudah tersimpan. Rancangan yang tahan gangguan adalah...', ['a'=>'Membatalkan seluruh data','b'=>'Menyimpan status pekerjaan dan mencoba reasoning ulang secara aman','c'=>'Menampilkan skor acak','d'=>'Menghapus attempt'], 'b', 'Pemisahan transaksi dan retry terkontrol mencegah kehilangan jawaban.'],
            'Data Modeling' => ['Satu mahasiswa dapat memiliki banyak attempt dan satu attempt milik tepat satu mahasiswa. Relasi yang sesuai adalah...', ['a'=>'One-to-many dari mahasiswa ke attempt','b'=>'One-to-one tanpa foreign key','c'=>'Many-to-many wajib','d'=>'Tidak perlu relasi'], 'a', 'Satu mahasiswa berhubungan dengan banyak record attempt melalui foreign key.'],
            'AI & Automation' => ['Rekomendasi karier berbasis aturan perlu dijelaskan kepada pengguna. Informasi yang paling berguna adalah...', ['a'=>'Kompetensi yang cocok, gap, aturan yang terpicu, dan keterbatasan','b'=>'Hanya satu angka akhir','c'=>'Nama model fiktif','d'=>'Animasi proses'], 'a', 'Penjelasan perlu menunjukkan dasar rekomendasi dan batas interpretasinya.'],
            'Machine Learning' => ['Akurasi training tinggi tetapi performa data baru rendah. Masalah yang paling mungkin adalah...', ['a'=>'Overfitting','b'=>'Normalisasi database','c'=>'DNS error','d'=>'CSS specificity'], 'a', 'Perbedaan besar antara training dan data baru merupakan tanda overfitting.'],
            'Presentation' => ['Waktu presentasi hanya lima menit. Struktur yang paling membantu pengambil keputusan adalah...', ['a'=>'Masalah, bukti utama, rekomendasi, risiko, dan keputusan yang dibutuhkan','b'=>'Membaca seluruh laporan','c'=>'Menampilkan semua source code','d'=>'Memakai animasi pada setiap kalimat'], 'a', 'Struktur ringkas mengarahkan audiens pada keputusan berbasis bukti.'],
            'Database Design' => ['Data pelanggan berulang di setiap baris pesanan sehingga alamat sulit diperbarui konsisten. Perbaikan struktur yang tepat adalah...', ['a'=>'Memisahkan pelanggan dan pesanan dengan foreign key','b'=>'Menambah kolom alamat lagi','c'=>'Menghapus primary key','d'=>'Menyimpan semuanya sebagai teks bebas'], 'a', 'Pemisahan entitas mengurangi duplikasi dan anomali pembaruan.'],
            'Data Visualization' => ['Grafik perlu membandingkan penjualan lima kategori pada satu periode. Bentuk yang paling mudah dibandingkan adalah...', ['a'=>'Bar chart dengan baseline yang sama','b'=>'Lima gauge','c'=>'Pie 3D','d'=>'Peta tanpa lokasi'], 'a', 'Panjang batang pada baseline bersama memudahkan perbandingan kategori.'],
            'Data Engineering' => ['Pipeline menerima event yang sama dua kali. Sifat proses yang mencegah duplikasi hasil adalah...', ['a'=>'Idempotent','b'=>'Recursive tanpa batas','c'=>'Anonymous','d'=>'State selalu global'], 'a', 'Pemrosesan idempotent menghasilkan keadaan sama saat input yang sama diulang.'],
            'Communication' => ['Temuan teknis berisiko menunda rilis. Pesan kepada stakeholder sebaiknya memuat...', ['a'=>'Fakta, dampak, pilihan tindakan, dan keputusan yang dibutuhkan','b'=>'Log mentah saja','c'=>'Jargon tanpa konteks','d'=>'Janji tanpa dasar'], 'a', 'Komunikasi kerja menghubungkan bukti dengan dampak dan tindakan.'],
            'Problem Solving' => ['Aplikasi lambat setelah perubahan terbaru. Langkah diagnosis awal yang paling kuat adalah...', ['a'=>'Membandingkan metrik sebelum dan sesudah, mempersempit komponen, lalu menguji satu hipotesis','b'=>'Mengganti seluruh stack','c'=>'Menambah server tanpa pengukuran','d'=>'Mengabaikan perubahan terakhir'], 'a', 'Diagnosis terarah menggunakan bukti, ruang lingkup, dan pengujian hipotesis.'],
        ];

        [$prompt, $options, $correct, $explanation] = $questions[$competency] ?? [
            "Sebuah hasil kerja perlu menunjukkan kompetensi {$competency}. Langkah evaluasi yang paling kuat adalah...",
            ['a'=>'Membandingkan hasil dengan kebutuhan dan bukti yang dapat diperiksa','b'=>'Memilih alat paling populer','c'=>'Mengabaikan konteks pengguna','d'=>'Mengubah hasil tanpa mencatat alasan'],
            'a',
            'Evaluasi kompetensi memerlukan kebutuhan, bukti, dan alasan yang dapat ditelusuri.',
        ];

        return compact('prompt', 'options', 'correct', 'explanation');
    }
}
